version: '3'
services:
  frontend:
    build:
      context: ./frontend # Adjust the path to your frontend folder
    ports:
      - "5174:5174" # Map Vite dev server port
    volumes:
      - ./frontend:/app # Sync local files for live development
      - /app/node_modules # Prevents overwriting node_modules
    command: yarn dev # Run Vite development server
    depends_on:
      - nodejs
      - python

  nodejs:
    build:
      context: ./backend # Adjust the path to your backend folder
    ports:
      - "4000:4000" # Expose backend port
    volumes:
      - ./backend:/app # Sync local files for live development
      - /app/node_modules # Prevents overwriting node_modules
      - logs:/app/logs # Shared volume for logs
    command: yarn dev # Run Node.js with nodemon in development mode
    depends_on:
      - python

  python:
    build:
      context: ./logs-generate # Adjust the path to your logs-generate folder
    volumes:
      - logs:/usr/src/app/logs # Shared volume for logs
    command: python3 script.py

volumes:
  logs:  # Declare the shared volume
