services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    command: yarn dev
    depends_on:
      - nodejs
      - python
    environment:
      - CHOKIDAR_USEPOLLING=true # For file watching in Docker

  nodejs:
    build:
      context: ./backend
    ports:
      - "5300:5300"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
      - logs:/app/logs
    command: yarn dev
    depends_on:
      - python
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # For file watching in Docker

  python:
    build:
      context: ./logs-generate
    volumes:
      - ./logs-generate:/usr/src/app
      - logs:/usr/src/app/logs
    command: python3 script.py

volumes:
  logs:
  node_modules_backend:
  node_modules_frontend:
